name: Deploy to Production Server

on:
  push:
    branches:
      - main  # Set this to whichever branches you want to trigger the deployment.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute SSH commands
      run: |
        ssh -o "StrictHostKeyChecking=no" ubuntu@ec2-3-101-124-150.us-west-1.compute.amazonaws.com "
          echo 'Connected successfully';
          cd csci181s-course-project/; 
          git pull;
          sudo systemctl enable server.service;
          sudo systemctl start server.service;
          sudo systemctl status server.service;
        "
